#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "This script needs to be run as root."
  exit 1
fi

IFACES=$(ip -o link show | awk -F': ' '{print $2}')
for IFACE in $IFACES; do
    if [ $IFACE != "lo" ]; then
        ip link set $IFACE down &>"/dev/null"
        macchanger -a $IFACE &>"/dev/null"
        ip link set $IFACE up &>"/dev/null"
    fi
done
